import type { LevelConfig } from "../engine/types";
import { EDUCATION, THESIS, WORK_EXPERIENCE, LEADERSHIP_EXPERIENCE, PROJECT_EXPERIENCE } from "../../data/resume";

// Helper to create platforms
function createPlatform(x: number, y: number, width: number, height: number, color: string) {
  return { x, y, width, height, type: "ground" as const, color };
}

// LEVEL 0: Tutorial Island
export const levelTutorial: LevelConfig = {
  id: 0,
  name: "Tutorial Island",
  width: 1200,
  height: 600,
  backgroundColor: "#87CEEB",
  theme: "university",
  startX: 50,
  startY: 450,
  exitX: 1100,
  exitY: 450,
  platforms: [
    createPlatform(0, 550, 300, 50, "#2C5F2D"),
    createPlatform(350, 500, 150, 50, "#97BC62FF"),
    createPlatform(550, 450, 150, 50, "#97BC62FF"),
    createPlatform(750, 500, 150, 50, "#97BC62FF"),
    createPlatform(950, 550, 250, 50, "#2C5F2D"),
  ],
  collectibles: [
    { x: 250, y: 500, width: 32, height: 32, type: "coin", value: 10, collected: false },
    { x: 400, y: 450, width: 32, height: 32, type: "coin", value: 10, collected: false },
    { x: 600, y: 400, width: 32, height: 32, type: "coin", value: 10, collected: false },
  ],
  npcs: [
    {
      x: 120,
      y: 550,
      width: 48,
      height: 64,
      name: "The Guide",
      role: "guide",
      dialog: [
        "Welcome, traveler! You're about to learn the story of a great hero...",
        "Isaiah Sam SD. Pascual - a Computer Science warrior who faced many challenges.",
        "Use Arrow Keys or A/D to move, Space/W to jump.",
        "Your journey begins at De La Salle University. Let's go!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 450,
      y: 500,
      width: 48,
      height: 64,
      name: "The Mentor",
      role: "guide",
      dialog: [
        "You're doing well! Isaiah's journey was filled with challenges.",
        "He collected knowledge and experience like you collect these coins.",
        "Each platform ahead represents a chapter in his story.",
        "Keep moving forward to discover who he truly is!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 1000,
      y: 550,
      width: 48,
      height: 64,
      name: "Portal Guardian",
      role: "guide",
      dialog: [
        "You've completed your training!",
        "The portal ahead leads to Isaiah's educational journey.",
        "Remember: Press ESC to pause, and you can return to menu anytime.",
        "Step through the EXIT when you're ready to begin!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
  ],
  checkpoints: [],
};

// LEVEL 1: Education Plains
export const level1: LevelConfig = {
  id: 1,
  name: "Education Plains",
  width: 2000,
  height: 600,
  backgroundColor: "#87CEEB",
  theme: "university",
  startX: 50,
  startY: 400,
  exitX: 1900,
  exitY: 400,
  platforms: [
    createPlatform(0, 500, 400, 100, "#2C5F2D"),
    createPlatform(450, 450, 200, 50, "#97BC62FF"),
    createPlatform(700, 400, 250, 50, "#97BC62FF"),
    createPlatform(1000, 350, 200, 50, "#97BC62FF"),
    createPlatform(1250, 450, 150, 50, "#97BC62FF"),
    createPlatform(1450, 500, 550, 100, "#2C5F2D"),
  ],
  collectibles: [
    { x: 500, y: 400, width: 32, height: 32, type: "credit", value: 10, collected: false },
    { x: 750, y: 350, width: 32, height: 32, type: "credit", value: 10, collected: false },
    { x: 1050, y: 300, width: 32, height: 32, type: "credit", value: 10, collected: false },
    { x: 1300, y: 400, width: 32, height: 32, type: "credit", value: 10, collected: false },
    { x: 1700, y: 450, width: 32, height: 32, type: "credit", value: 10, collected: false },
  ],
  npcs: [
    {
      x: 200,
      y: 500,
      width: 48,
      height: 64,
      name: "Dean Martinez",
      role: "researcher",
      dialog: [
        `Welcome to ${EDUCATION.university}, where Isaiah's journey began!`,
        `From October 2021 to December 2025, he pursued ${EDUCATION.degree}.`,
        `He maintained a ${EDUCATION.gpa} while balancing academics and real-world projects.`,
        `This university shaped him into the professional he would become.`,
        "The challenges ahead will test everything he learned here!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 1600,
      y: 500,
      width: 48,
      height: 64,
      name: "Professor Chen",
      role: "researcher",
      dialog: [
        "Isaiah graduated with honors from this prestigious institution!",
        "But education was just the foundation of his story.",
        "Next, he embarked on his thesis - a groundbreaking research project.",
        "The Thesis Lab awaits beyond this exit!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
  ],
  checkpoints: [
    { x: 800, y: 270, width: 40, height: 50, id: "cp1", activated: false, label: "Midpoint" },
  ],
};

// LEVEL 2: Thesis Lab (GRASP)
export const level2: LevelConfig = {
  id: 2,
  name: "Thesis Lab (GRASP)",
  width: 2200,
  height: 600,
  backgroundColor: "#2C3E50",
  theme: "research",
  startX: 50,
  startY: 400,
  exitX: 2100,
  exitY: 200,
  platforms: [
    createPlatform(0, 500, 350, 100, "#34495E"),
    createPlatform(400, 450, 150, 50, "#5D6D7E"),
    createPlatform(600, 400, 150, 50, "#5D6D7E"),
    createPlatform(800, 350, 200, 50, "#5D6D7E"),
    createPlatform(1050, 400, 150, 50, "#5D6D7E"),
    createPlatform(1250, 450, 150, 50, "#5D6D7E"),
    createPlatform(1450, 350, 200, 50, "#5D6D7E"),
    createPlatform(1700, 300, 150, 50, "#5D6D7E"),
    createPlatform(1900, 250, 300, 50, "#34495E"),
  ],
  collectibles: [
    { x: 450, y: 400, width: 32, height: 32, type: "component", value: 25, collected: false },
    { x: 650, y: 350, width: 32, height: 32, type: "component", value: 25, collected: false },
    { x: 850, y: 300, width: 32, height: 32, type: "component", value: 25, collected: false },
    { x: 1100, y: 350, width: 32, height: 32, type: "component", value: 25, collected: false },
  ],
  npcs: [
    {
      x: 150,
      y: 500,
      width: 48,
      height: 64,
      name: "Dr. Santos",
      role: "researcher",
      dialog: [
        `This is where Isaiah created ${THESIS.title} - ${THESIS.fullTitle}.`,
        `From ${THESIS.dates}, he worked tirelessly on this project.`,
        "He led the entire engineering lifecycle - from requirements to validation.",
        "Using Python, MediaPipe, and OpenCV, he built something remarkable.",
        "Collect the components ahead to see what he achieved!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 500,
      y: 450,
      width: 48,
      height: 64,
      name: "Tech Lead Ada",
      role: "engineer",
      dialog: [
        "You've discovered the Python pipeline Isaiah built!",
        "He used Python to create machine learning models for gesture recognition.",
        "This was the foundation of his authentication system.",
        "Keep going to see the full picture!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 900,
      y: 350,
      width: 48,
      height: 64,
      name: "Researcher Kim",
      role: "engineer",
      dialog: [
        "Isaiah integrated MediaPipe for real-time gesture detection!",
        "This allowed the system to recognize hand movements accurately.",
        "He combined it with OpenCV for computer vision processing.",
        "The innovation was in how he brought these technologies together!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 1500,
      y: 350,
      width: 48,
      height: 64,
      name: "Dr. Reyes",
      role: "researcher",
      dialog: [
        "The results of Isaiah's thesis were extraordinary!",
        `He achieved ${THESIS.metrics.gestureAccuracy}% gesture recognition accuracy through rigorous testing.`,
        `Even more impressive: ${THESIS.metrics.spoofRejection}% spoof rejection rate!`,
        "This meant the system could detect fake authentication attempts perfectly.",
        "His work proved he could deliver production-ready machine learning systems!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
  ],
  checkpoints: [
    { x: 1000, y: 220, width: 40, height: 50, id: "cp2", activated: false, label: "Pipeline" },
  ],
};

// LEVEL 3: Shopee City
export const level3: LevelConfig = {
  id: 3,
  name: "Shopee City: Fraud Patrol",
  width: 2400,
  height: 600,
  backgroundColor: "#1A1A2E",
  theme: "fraud-detection",
  startX: 50,
  startY: 400,
  exitX: 2300,
  exitY: 350,
  platforms: [
    createPlatform(0, 500, 300, 100, "#16213E"),
    createPlatform(350, 450, 180, 50, "#0F3460"),
    createPlatform(580, 400, 160, 50, "#0F3460"),
    createPlatform(790, 350, 140, 50, "#0F3460"),
    createPlatform(980, 400, 200, 50, "#0F3460"),
    createPlatform(1230, 350, 180, 50, "#0F3460"),
    createPlatform(1460, 300, 160, 50, "#0F3460"),
    createPlatform(1670, 350, 180, 50, "#0F3460"),
    createPlatform(1900, 400, 500, 100, "#16213E"),
  ],
  collectibles: [
    { x: 400, y: 400, width: 32, height: 32, type: "badge", value: 30, collected: false },
    { x: 630, y: 350, width: 32, height: 32, type: "badge", value: 30, collected: false },
    { x: 840, y: 300, width: 32, height: 32, type: "badge", value: 30, collected: false },
    { x: 1030, y: 350, width: 32, height: 32, type: "badge", value: 30, collected: false },
    { x: 1280, y: 300, width: 32, height: 32, type: "badge", value: 30, collected: false },
  ],
  npcs: [
    {
      x: 150,
      y: 500,
      width: 48,
      height: 64,
      name: "Manager Liu",
      role: "leader",
      dialog: [
        `Welcome to ${WORK_EXPERIENCE[0].company} in Ortigas, Philippines!`,
        `Isaiah was a ${WORK_EXPERIENCE[0].role} here from ${WORK_EXPERIENCE[0].dates}.`,
        "In just three months, he made a massive impact on the fraud detection team.",
        "He led the development of an offline fraud detection solution...",
        "...combining machine learning models with rule-based automation!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 800,
      y: 350,
      width: 48,
      height: 64,
      name: "Engineer Wong",
      role: "engineer",
      dialog: [
        "Isaiah's fraud detection models were game-changing!",
        `He improved detection rates by ${WORK_EXPERIENCE[0].metrics.detectionImprovement}% - a massive leap forward!`,
        "The system transitioned from testing to production operations.",
        "Shopee's platform became significantly safer because of his work!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 1280,
      y: 350,
      width: 48,
      height: 64,
      name: "Data Scientist Park",
      role: "engineer",
      dialog: [
        "Let me tell you about the scale Isaiah operated at...",
        `He processed over ${WORK_EXPERIENCE[0].metrics.listingsProcessed} listings using Python-based pipelines!`,
        `The system achieved ${WORK_EXPERIENCE[0].metrics.detectionAccuracy}% detection accuracy at that scale!`,
        "This wasn't just a prototype - it was production-grade data engineering.",
        "Scalable and repeatable - that was Isaiah's standard!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 2100,
      y: 400,
      width: 48,
      height: 64,
      name: "Director Tan",
      role: "leader",
      dialog: [
        "Isaiah's fraud detection system is now protecting millions of users!",
        "He proved himself as a leader who could deliver real business impact.",
        "But this was just one chapter of his journey...",
        "Before Shopee, he honed his skills at another major company!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
  ],
  checkpoints: [
    { x: 1000, y: 270, width: 40, height: 50, id: "cp3-1", activated: false, label: "Scan-1" },
    { x: 1500, y: 170, width: 40, height: 50, id: "cp3-2", activated: false, label: "Scan-2" },
  ],
};

// LEVEL 4: Asurion QA Towers
export const level4: LevelConfig = {
  id: 4,
  name: "Asurion QA Towers",
  width: 2000,
  height: 700,
  backgroundColor: "#ECF0F1",
  theme: "testing",
  startX: 50,
  startY: 550,
  exitX: 1900,
  exitY: 150,
  platforms: [
    createPlatform(0, 650, 300, 50, "#BDC3C7"),
    createPlatform(350, 600, 150, 50, "#95A5A6"),
    createPlatform(550, 550, 150, 50, "#95A5A6"),
    createPlatform(750, 500, 150, 50, "#95A5A6"),
    createPlatform(950, 450, 150, 50, "#95A5A6"),
    createPlatform(1150, 400, 150, 50, "#95A5A6"),
    createPlatform(1350, 350, 150, 50, "#95A5A6"),
    createPlatform(1550, 300, 150, 50, "#95A5A6"),
    createPlatform(1750, 200, 250, 50, "#BDC3C7"),
  ],
  collectibles: [
    { x: 400, y: 550, width: 32, height: 32, type: "badge", value: 20, collected: false },
    { x: 600, y: 500, width: 32, height: 32, type: "badge", value: 20, collected: false },
    { x: 800, y: 450, width: 32, height: 32, type: "badge", value: 20, collected: false },
    { x: 1000, y: 400, width: 32, height: 32, type: "badge", value: 20, collected: false },
    { x: 1200, y: 350, width: 32, height: 32, type: "badge", value: 20, collected: false },
  ],
  npcs: [
    {
      x: 150,
      y: 650,
      width: 48,
      height: 64,
      name: "QA Manager Davis",
      role: "qa",
      dialog: [
        `Welcome to ${WORK_EXPERIENCE[1].company} in Taguig!`,
        `Isaiah was a ${WORK_EXPERIENCE[1].role} from ${WORK_EXPERIENCE[1].dates}.`,
        `He owned the automation strategy for ${WORK_EXPERIENCE[1].metrics.clientApps} different client applications!`,
        "This required designing entire test automation frameworks from scratch.",
        "Climb the QA towers to see what he accomplished!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 600,
      y: 550,
      width: 48,
      height: 64,
      name: "Test Engineer Miller",
      role: "qa",
      dialog: [
        "Isaiah integrated JavaScript and Selenium into the QA process!",
        "He streamlined the entire software testing lifecycle.",
        "This improved release reliability across all client applications.",
        "Every switch you activate represents a system he automated!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 1000,
      y: 450,
      width: 48,
      height: 64,
      name: "Automation Lead Chen",
      role: "qa",
      dialog: [
        "The numbers speak for themselves...",
        `Isaiah increased automation coverage from ${WORK_EXPERIENCE[1].metrics.coverageFrom}% to ${WORK_EXPERIENCE[1].metrics.coverageTo}%!`,
        "That's not just an improvement - that's a transformation!",
        "He turned manual testing into an automated, reliable process.",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 1400,
      y: 350,
      width: 48,
      height: 64,
      name: "Senior QA Johnson",
      role: "qa",
      dialog: [
        "The Selenium framework Isaiah deployed is still in use today!",
        "His work improved operational efficiency across the entire QA department.",
        "He didn't just write tests - he built sustainable systems.",
        "Now you understand his dedication to quality and reliability!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
  ],
  checkpoints: [
    { x: 800, y: 370, width: 40, height: 50, id: "cp4", activated: false, label: "Tower-3" },
  ],
};

// LEVEL 5: Leadership Castle
export const level5: LevelConfig = {
  id: 5,
  name: "Leadership Castle",
  width: 2600,
  height: 600,
  backgroundColor: "#8E44AD",
  theme: "leadership",
  startX: 50,
  startY: 400,
  exitX: 2500,
  exitY: 250,
  platforms: [
    createPlatform(0, 500, 350, 100, "#9B59B6"),
    createPlatform(400, 450, 150, 50, "#BB8FCE"),
    createPlatform(600, 400, 150, 50, "#BB8FCE"),
    createPlatform(800, 350, 200, 50, "#BB8FCE"),
    createPlatform(1050, 400, 150, 50, "#BB8FCE"),
    createPlatform(1250, 350, 180, 50, "#BB8FCE"),
    createPlatform(1480, 300, 160, 50, "#BB8FCE"),
    createPlatform(1690, 350, 150, 50, "#BB8FCE"),
    createPlatform(1890, 400, 150, 50, "#BB8FCE"),
    createPlatform(2090, 300, 510, 100, "#9B59B6"),
  ],
  collectibles: [
    { x: 450, y: 400, width: 32, height: 32, type: "token", value: 35, collected: false },
    { x: 650, y: 350, width: 32, height: 32, type: "token", value: 35, collected: false },
    { x: 1100, y: 350, width: 32, height: 32, type: "token", value: 35, collected: false },
    { x: 1530, y: 250, width: 32, height: 32, type: "token", value: 35, collected: false },
  ],
  npcs: [
    {
      x: 150,
      y: 500,
      width: 48,
      height: 64,
      name: "Dean Rodriguez",
      role: "leader",
      dialog: [
        "Welcome to Leadership Castle!",
        `Isaiah was the ${LEADERSHIP_EXPERIENCE[0].role} for ${LEADERSHIP_EXPERIENCE[0].organization}.`,
        `From ${LEADERSHIP_EXPERIENCE[0].dates}, he led an ${LEADERSHIP_EXPERIENCE[0].metrics?.teamSize}-member executive team!`,
        "He managed engineering delivery for the College of Computer Studies' web systems.",
        "His leadership transformed how the college approached software development!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 500,
      y: 450,
      width: 48,
      height: 64,
      name: "Developer Garcia",
      role: "engineer",
      dialog: [
        "Isaiah defined the technical roadmap for the ONECCS platform!",
        "He led the migration from Google Sites to React and Node.js architecture.",
        "This improved maintainability, deployment control, and scalability.",
        "He didn't just code - he architected the future of the system!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 1100,
      y: 400,
      width: 48,
      height: 64,
      name: "UX Lead Torres",
      role: "leader",
      dialog: [
        `Isaiah was the ${LEADERSHIP_EXPERIENCE[1].role} for ${LEADERSHIP_EXPERIENCE[1].organization}!`,
        "He contributed to architecture for a university-wide web application.",
        "Using React and JavaScript, he balanced user experience with technical constraints.",
        "He helped establish development best practices and MongoDB-backed environments.",
        "His contributions are still serving students across the university today!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 1740,
      y: 350,
      width: 48,
      height: 64,
      name: "Director Lim",
      role: "leader",
      dialog: [
        `As ${LEADERSHIP_EXPERIENCE[2].role} for ${LEADERSHIP_EXPERIENCE[2].organization}...`,
        `Isaiah served from ${LEADERSHIP_EXPERIENCE[2].dates}.`,
        "He spearheaded cross-functional delivery teams across multiple initiatives!",
        "He coordinated timelines, resources, and execution with operational discipline.",
        "His workshops on logistics optimization improved team capability and efficiency!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 2200,
      y: 300,
      width: 48,
      height: 64,
      name: "Event Coordinator Cruz",
      role: "leader",
      dialog: [
        `For ${LEADERSHIP_EXPERIENCE[3].organization}, Isaiah was the ${LEADERSHIP_EXPERIENCE[3].role}!`,
        `This was in ${LEADERSHIP_EXPERIENCE[3].dates} - a critical recruitment event.`,
        `He pioneered a high-traffic platform serving the entire DLSU student body!`,
        `The platform handled ${LEADERSHIP_EXPERIENCE[3].metrics?.pageLoads} unique page loads with perfect reliability!`,
        "React + ExpressJS + MongoDB - Isaiah's go-to stack for scalable systems!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
  ],
  checkpoints: [
    { x: 900, y: 220, width: 40, height: 50, id: "cp5-1", activated: false, label: "Hall-1" },
    { x: 1700, y: 170, width: 40, height: 50, id: "cp5-2", activated: false, label: "Hall-2" },
  ],
};

// LEVEL 6: NurseLink Network Docks
export const level6: LevelConfig = {
  id: 6,
  name: "NurseLink Network Docks",
  width: 1800,
  height: 600,
  backgroundColor: "#16A085",
  theme: "fullstack",
  startX: 50,
  startY: 400,
  exitX: 1700,
  exitY: 350,
  platforms: [
    createPlatform(0, 500, 300, 100, "#1ABC9C"),
    createPlatform(350, 450, 180, 50, "#48C9B0"),
    createPlatform(580, 400, 160, 50, "#48C9B0"),
    createPlatform(790, 450, 140, 50, "#48C9B0"),
    createPlatform(980, 400, 200, 50, "#48C9B0"),
    createPlatform(1230, 450, 160, 50, "#48C9B0"),
    createPlatform(1440, 400, 360, 100, "#1ABC9C"),
  ],
  collectibles: [
    { x: 400, y: 400, width: 32, height: 32, type: "crate", value: 40, collected: false },
    { x: 630, y: 350, width: 32, height: 32, type: "crate", value: 40, collected: false },
    { x: 1030, y: 350, width: 32, height: 32, type: "crate", value: 40, collected: false },
  ],
  npcs: [
    {
      x: 150,
      y: 500,
      width: 48,
      height: 64,
      name: "Dr. Anderson",
      role: "healthcare",
      dialog: [
        `Welcome to the ${PROJECT_EXPERIENCE[0].project} Network Docks!`,
        `Isaiah was the ${PROJECT_EXPERIENCE[0].role} from ${PROJECT_EXPERIENCE[0].dates}.`,
        "He owned the full-stack development of a healthcare professional networking platform.",
        "He translated complex business requirements into technical solutions.",
        "Let me show you the features he built for the healthcare community!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 450,
      y: 450,
      width: 48,
      height: 64,
      name: "Backend Dev Smith",
      role: "engineer",
      dialog: [
        "Isaiah built a complete user authentication system!",
        "Using React for the frontend and Node.js for the backend...",
        "He ensured healthcare professionals could securely access the platform.",
        "Security was paramount for this sensitive healthcare application!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 840,
      y: 450,
      width: 48,
      height: 64,
      name: "Database Admin Lee",
      role: "engineer",
      dialog: [
        "The professional profile system was impressively architected!",
        "Isaiah used MongoDB to model complex healthcare professional data.",
        "Profiles, credentials, specializations - all efficiently structured.",
        "His database design made the platform scalable from day one!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
    {
      x: 1600,
      y: 400,
      width: 48,
      height: 64,
      name: "Product Owner Martinez",
      role: "leader",
      dialog: [
        "Isaiah delivered a production-ready system ahead of schedule!",
        "The client handoff was smooth - full documentation and operational continuity.",
        "All features were tested, secure, and ready for healthcare professionals to use.",
        "He proved he could own projects from start to finish!",
        "This is who Isaiah Sam SD. Pascual is - a complete professional!",
      ],
      dialogIndex: 0,
      active: true,
      interactionRadius: 80,
    },
  ],
  checkpoints: [
    { x: 1000, y: 270, width: 40, height: 50, id: "cp6", activated: false, label: "Dock-2" },
  ],
};

export const LEVELS: LevelConfig[] = [levelTutorial, level1, level2, level3, level4, level5, level6];
